allow opening the editor on dotfiles from anywhere

diff --git a/m/commands/dotfiles b/m/commands/dotfiles
--- a/m/commands/dotfiles
+++ b/m/commands/dotfiles
@@ -3,14 +3,16 @@
 function usage {
   cat<<__EOF__
 
-    usage: m dotfiles [help | sync | setup]
+    usage: m dotfiles [help | sync | setup | edit]
 
 
     Examples:
-      m dotfiles help             # prints this help message
-      m dotfiles pull             # pull the latest changes to the dotfiles repo by running
-                                  # this includes this command itself and will implicitly update it
-      m dotfiles setup            # sets up the dotfiles repo for the first time in a system
+      m dotfiles help                              # prints this help message
+      m dotfiles pull                              # pull the latest changes to the dotfiles repo by running
+                                                   # this includes this command itself and will implicitly update it
+      m dotfiles setup                             # sets up the dotfiles repo for the first time in a system
+      m dotfiles edit [--with <editor>]            # opens the dotfiles repo in an editor, defaults to EDITOR env var or vim
+                                                   # if "--with" is passed with an editor it is used instead
 
 __EOF__
 
@@ -42,6 +44,21 @@ case "${cmd}" in
     done
 
     popd
+    ;;
+
+  edit)
+    editor="${EDITOR-vim}"
+    if [ ! -z "$1" ] && [ "$1" = '--with' ] && [ ! -z "$2" ]; then
+      editor="${2}"
+    elif [ ! -z "$1" ] && [ "$1" = '--with' ] && [ -z "$2" ]; then
+      echo "Missing editor to be passed with config" >&2
+      exit 1
+    elif [ ! -z "$1" ]; then
+      echo "Unknown option passed" >&2
+      exit 1
+    fi
+
+    $editor "${DOTFILES_PATH}"
     ;;
 
   help)
